language: python

dist: xenial

python:
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
      - libgconf-2-4

env:
  - CYPRESS_VIDEO=false
    FILENAME=/tmp/image/context.tar
    DOCKER_PLATFORM=linux/386,linux/arm64,linux/amd64,linux/arm/v7,linux/arm/v6 
    TARGET_IMAGE=delfick/lifx-photons-interactor

install:
  - pip install pip --upgrade
  - pip install -e "modules[tests]"
  - pip install -e "apps/interactor"

script:
  - cd modules && ./test.sh -v
  - cd ../apps/interactor && ./test.sh

jobs:
  include:
    - stage: deploy
      script: skip
      addons: skip
      install: skip
      before_script: skip

      if: tag IS present

      before_deploy:
        - pip install venvstarter
        - mkdir /tmp/image
        - ./docker/harpoon get_docker_context lifx-photons-interactor 

        - curl -fsSL https://get.docker.com | sh
        - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
        - mkdir -p $HOME/.docker
        - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
        - sudo service docker start

        - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - docker buildx create --name xbuilder --use

        - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

      deploy:
        provider: script
        skip_cleanup: true
        on:
          tags: true

        script: >-
          cd /tmp/image
          && tar xf context.tar
          && docker buildx build --progress plain --platform $DOCKER_PLATFORM --push -t ${TARGET_IMAGE}:${TRAVIS_TAG} -t ${TARGET_IMAGE}:latest .
