---

name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install deps
        shell: bash
        env:
          VENVSTARTER_ONLY_MAKE_VENV: "1"
        run: python ./tools/venv

      - name: Ensure linter is happy
        run: ./lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install deps
        shell: bash
        env:
          VENVSTARTER_ONLY_MAKE_VENV: "1"
        run: python ./tools/venv

      - name: Ensure code is formatted
        run: |
          ./format

          # Complain if there were changes
          if [[ ! -z "$(git status --porcelain)" ]]; then
            echo "=========================================="
            echo "Found changes!"
            echo "Please run ./format before committing code"
            echo "=========================================="
            git diff
            exit 1
          fi
